
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/ClientCare_Desktop/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#F6F6F6] py-4 px-2 md:flex md:flex-col md:justify-center md:items-center">
            <Header />
            <div className="bg-[#E7E7E7] w-full h-1 my-2 md:w-4/5 md:max-w-5xl"></div>
            

            {children}
        </div>
      </body>
    </html>
  );
}
