
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/ClientCare/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="md:w-full md:flex md:items-center md:justify-center">
          <div className="bg-[#F6F6F6] pb-3">
            <Header />
            <div className="bg-[#E7E7E7] w-full h-1 mt-2"></div>
            <div className="mt-2">
                  {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
